baseURL       = "https://danajardell.github.io/"
languageCode  = "en-us"
title         = "Dana J Ardell | UX Designer"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/Logomark_Final.svg"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/dana-profile-photo-web.jpg"
    heading               = "Consectetur adipiscing elit, sed do eiusmod tempor"
    tagline               = "Lorem ipsum dolor sit amet"
    primary_button        = "My Work"
    primary_button_url    = "portfolio"
    secondary_button      = "My Info"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "RECENT WORK"
    subtitle  = "Sed turpis tincidunt id aliquet. Elit ullamcorper dignissim cras tincidunt."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      email   = "danajardell@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Work"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Lorem ipsum dolor sit amet:"
        description = "consectetur adipiscing<br>elit, sed do eiusmod<br>elit, sed do eiusmod"